misc:
  range: 45
  cooldown: 2000 # Cooldown in millisecondi (1s = 1000ms)

db:
  url: localhost
  user: root
  password: ""
  port: 3306
  database: quake

perms:
  get: quake.get
  reload: quake.reload