misc:
  range: 45
  cooldown: 2000 # Cooldown in millisecondi (1s = 1000ms)
  required_score: 10

db:
  url: localhost
  user: root
  password: ""
  port: 3306
  database: quake

perms:
  quake:
    get: quake.get
    reload: quake.reload
  arena:
    command: arena.command
    setup: arena.setup
    delete: arena.delete

msg:
  arena:
    spawn_added: "&aSpawn Aggiunto"
    created: "&aArena Creata. Usa i comandi di /arena <sub-command> per impostarla"
    deleted: "&aArena Eliminata."
    finished: "&aArena finita. Usa /quake join <nome> per entrarci."
    not_finished: "&cNon hai impostato tutti i parametri"
    lobby_set: "&aLobby Impostata"
    max_players_set: "&aPlayer Massimi impostati"
    min_players_set: "&aPlayer Minimi impostati"
    stopped_creating: "&aHai smesso di creare l'arena."
    left: "&aHai lasciato l'arena"
    reloaded: "&aConfig ricaricato"
    joined: "&7%name% &aè entrato nell'arena &7(%current%/%max%)"
    you_joined: "&aSei entrato nell'arena"
    starting: "&aIl gioco inizierà in %tempo% secondi"
    game_over: "&aPartita finita. %player% vince"
    hit: "&aHai colpito %player%"
    got_hit: "&aSei stato colpito da %player%"
  errors:
    args: "&cArgomenti Sbagliati."
    not_player: "La console non può usare questo comando"
    not_creating: "&cNon stai creando un'arena. Usa /arena create <nome>"
    no_perms: "&cNon hai abbastanza permessi"
    already_creating: "&cStai già creando un'arena, per uscire usa /arena cancel"
    arg_not_found: "&cQuesto sub-command non esiste."
    arena_not_found: "&cQuesta arena non esiste"
    not_a_number: "&cL'argomento deve essere un numero"
    already_playing: "&cSei già in un game. Usa /quake leave per uscire"
    not_playing: "&cNon sei in un game. Usa /quake join <arena> per entrare"
    recharging: "&cL'arma sta ricaricando. (%tempo% s)"
    full: "&cArena piena"