misc:
  range: 45
  cooldown: 2000 # Cooldown in millisecondi (1s = 1000ms)
  required_score: 10

db:
  url: localhost
  user: root
  password: ""
  port: 3306
  database: quake

perms:
  quake:
    get: quake.get
    reload: quake.reload
  arena:
    command: arena.command
    setup: arena.setup